# Generated by Django 3.0.4 on 2021-09-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_summarization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesupload',
            old_name='file',
            new_name='myFile',
        ),
    ]
