# Generated by Django 3.0.4 on 2021-09-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_summarization', '0003_auto_20210914_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesupload',
            old_name='myFile',
            new_name='files',
        ),
    ]
