# Generated by Django 3.0.4 on 2021-09-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_summarization', '0004_auto_20210914_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesUpload',
        ),
    ]
